markdown: redcarpet
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Steve O'Keefe
url: http://nlsteveo.github.io
description: this is a test. hello world.
twitter: nlsteveo
