# Site settings
title: Steve O'Keefe
description: Steve O'Keefe's Website
favicon: /assets/img/AVATAR.jpg
baseurl:
url: 
rss_url: /pages/atom.xml

# Build settings
markdown: kramdown

# Author settings
author:
  name: Steve O'Keefe
  title: Software Developer
  address: St. John's, NL, Canada
  email: steveokeefe88@gmail.com
  link: 
  weibo:
  github: nlsteveo
  linkedin: nlsteveo
  twitter: nlsteveo
  gavatar: /assets/img/AVATAR.jpg
  workHistory:
    - work1:
      company: Wood
      location: St. John's, NL
      title: Software Developer
      started: 2015
      duration: (2015 - Present)
      description: Developer on a team that follows the agile methodology and uses Atlassian suite of project management tools like JIRA, and BitBucket. Working as the primary developer on a couple projects, one using JavaScript and ArcGIS software with a C# backend, and another that uses Node.js for it's server side while the frontend uses ReactJS. Manage and run many of our systems on AWS. Optimized and updated older and current smaller projects as needed. Other tools used are MS SQL, PostgreSQL, Python, Docker.
    - work2:
      company: Suncor Energy
      location: St. John's, NL
      title: General Contractor
      started: 2015
      duration: (2015)
      description: Contracted for about 6 weeks packing up files to be moved offsite in preparation for office relocation. Got extended by 3 more weeks(because thats when I got a new job as Software Developer) and assigned additional duties, which include scanning invoices to be entered into documentum(Software used for storing documents).
    - work3:
      company: Marie's Bakery
      location: St. John's, NL
      title: Deli Server
      started: 2013
      duration: (2013 - 2015)
      description: Usual duties include serving customers from the bakery/deli and serving hot meals during weekdays. Also, preparing orders for drivers to deliver to the other stores, helping receive shipments from suppliers, helping train new employees, and assisting the bakers by packaging product.
    - work4:
      company: Wallnuts Climbing Centre
      location: St. John's, NL
      title: Belayer
      started: 2013
      duration: (2013 - Present)
      description: Usual duties are providing safe and practised belays for various types of climbing groups of all ages and providing clear communication and presentation of safety and rules of climbing, for Wallnuts Climbing Centre.
    - work5:
      company: McDonald's
      location: St. John's, NL
      title: Crew / Crew Trainer / Swing Manager
      started: 2005
      duration: (2005 - 2013)
      multiDescription:
        - section1:
          description: (Swing Manager) - Usual duties included balancing payroll and cashes, while responsible for managing the operation of the store and employees. Awarded swing manager of the month and top of the class in my Basic Shift Management course.
        - section2:
          description: (Crew Trainer) - Assisted the managers in their daily tasks and running the floor. Trained new and current employees throughout various positions, while also being the lead trainer in training other trainers and employees in new products and procedures. Delegated various tasks to crew members. Awarded employee of the month and employee of the year(2009).
        - section3:
          description: (Crew) - Was trained in all crew positions throughout all stations in the store. Awarded employee of the month twice and first time while still a rookie.
    - work6:
      company: Computer Science Department of Memorial University
      location: St. John's, NL
      title: Future Pathways Student
      started: 2005
      duration: (2005)
      description: Performed tasks such as cleaning a database, installing linux, troubleshooting computers with unknown problems, collecting information for a database, and creating a CGI script for python over a two month work term.
  educationHistory:
    - education1:
      organization: Memorial University of Newfoundland and Labrador
      degree: Bachelor of Science
      major: Computer Science
      finished: 2015
      graduated: 2015
      description: I started university persuing Computer engineering but after a few years I decided that I would like Computer Science more and changed degrees. While in Computer Science I had some choice in courses I took and some of those were CS1400 - Computing in the 20th century(Taught the history of computing and where we may see it going), CS1600 - Basic Computing and Information Technology(Taught Microsoft office with depth especially excell and access), CS2718 - Dev Tools, Work Flows & Concepts(Taught bash, ant, git, and some eclipse), CS3710 - Vocational Languages(Taught prolog, C, and C++), CS4743 - Graph Algorithms, and CS4768 - Software Development for Mobile Devices(Taught iOS development using xcode and objective-c).
  environments:
    - environment1:
      name: Windows
    - environment2:
      name: Linux
    - environment3:
      name: Git
    - environment4:
      name: AWS
    - environment5:
      name: Docker
    - environment6:
      name: JIRA
  programmingSkills:
    - skill1:
      name: Node.js
    - skill2:
      name: ReactJS
    - skill3:
      name: JavaScript
    - skill4:
      name: C#
    - skill5:
      name: Python
    - skill6:
      name: Java
